path: /kaggle/input/images-of-common-pets/datasets
train: train/images
val: test/images

nc: 10

names:
    0: bird
    1: cat
    2: dog
    3: lizard
    4: guinea pig
    5: hamster
    6: fish
    7: horse
    8: rabbit
    9: turtle